// flow-typed signature: ab3f39738b03b3d6ad60efdda8d8f48f
// flow-typed version: <<STUB>>/auth0-lock_v11.24.5/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-lock' {
  declare module.exports: any;
}
