/*
 * @flow
 */

// TODO: entity set names must be dynamic, hardcoding for now
const ASSOCIATION_ENTITY_SET_NAMES = {
  DECRYPTED_BY_ESN: 'DECRYPTED_BY_ESN',
  INCLUDES_ESN: 'INCLUDES_ESN',
  LOCATED_AT_ESN: 'LOCATED_AT_ESN',
  SIGNED_BY_ESN: 'SIGNED_BY_ESN',
  VERIFIES_ESN: 'VERIFIES_ESN',
};

// TODO: entity set names must be dynamic, hardcoding for now
const ENTITY_SET_NAMES = {
  CLIENTS_ESN: 'CLIENTS_ESN',
  CONSENT_FORM_ESN: 'CONSENT_FORM_ESN',
  CONSENT_FORM_SCHEMAS_ESN: 'CONSENT_FORM_SCHEMAS_ESN',
  DIGITAL_SIGNATURE_ESN: 'DIGITAL_SIGNATURE_ESN',
  ELECTRONIC_SIGNATURE_ESN: 'ELECTRONIC_SIGNATURE_ESN',
  LOCATION_ESN: 'LOCATION_ESN',
  PUBLIC_KEY_ESN: 'PUBLIC_KEY_ESN',
  STAFF_ESN: 'STAFF_ESN',
  WITNESSES_ESN: 'WITNESSES_ESN',
};


export {
  ASSOCIATION_ENTITY_SET_NAMES,
  ENTITY_SET_NAMES,
};
