
/*
 * @flow
 */

const CLIENTS_ESID :'CLIENTS_ESID' = 'CLIENTS_ESID';
const CONSENT_FORMS_ESID :'CONSENT_FORMS_ESID' = 'CONSENT_FORMS_ESID';
const CONSENT_FORM_SCHEMAS_ESID :'CONSENT_FORM_SCHEMAS_ESID' = 'CONSENT_FORM_SCHEMAS_ESID';
const DECRYPTED_BY_ESID :'DECRYPTED_BY_ESID' = 'DECRYPTED_BY_ESID';
const DIGITAL_SIGNATURES_ESID :'DIGITAL_SIGNATURES_ESID' = 'DIGITAL_SIGNATURES_ESID';
const ELECTRONIC_SIGNATURES_ESID :'ELECTRONIC_SIGNATURES_ESID' = 'ELECTRONIC_SIGNATURES_ESID';
const INCLUDES_ESID :'INCLUDES_ESID' = 'INCLUDES_ESID';
const LOCATED_AT_ESID :'LOCATED_AT_ESID' = 'LOCATED_AT_ESID';
const LOCATION_ESID :'LOCATION_ESID' = 'LOCATION_ESID';
const PUBLIC_KEYS_ESID :'PUBLIC_KEYS_ESID' = 'PUBLIC_KEYS_ESID';
const SIGNED_BY_ESID :'SIGNED_BY_ESID' = 'SIGNED_BY_ESID';
const STAFF_ESID :'STAFF_ESID' = 'STAFF_ESID';
const VERIFIES_ESID :'VERIFIES_ESID' = 'VERIFIES_ESID';
const WITNESSES_ESID :'WITNESSES_ESID' = 'WITNESSES_ESID';

export {
  CLIENTS_ESID,
  CONSENT_FORMS_ESID,
  CONSENT_FORM_SCHEMAS_ESID,
  DECRYPTED_BY_ESID,
  DIGITAL_SIGNATURES_ESID,
  ELECTRONIC_SIGNATURES_ESID,
  INCLUDES_ESID,
  LOCATED_AT_ESID,
  LOCATION_ESID,
  PUBLIC_KEYS_ESID,
  SIGNED_BY_ESID,
  STAFF_ESID,
  VERIFIES_ESID,
  WITNESSES_ESID,
};

const CLIENT_EKID :'CLIENT_EKID' = 'CLIENT_EKID';
const FORM_EKID :'FORM_EKID' = 'FORM_EKID';
const SCHEMA_EKID :'SCHEMA_EKID' = 'SCHEMA_EKID';
const STAFF_EKID :'STAFF_EKID' = 'STAFF_EKID';

export {
  CLIENT_EKID,
  FORM_EKID,
  SCHEMA_EKID,
  STAFF_EKID,
};
