
/*
 * @flow
 */

type QueryStringParamEnum = {|
  CLIENTS_ESID :'CLIENTS_ESID';
  CLIENT_EKID :'CLIENT_EKID';
  CONSENT_FORM_ESID :'CONSENT_FORM_ESID';
  CONSENT_FORM_SCHEMAS_ESID :'CONSENT_FORM_SCHEMAS_ESID';
  DECRYPTED_BY_ESID :'DECRYPTED_BY_ESID';
  DIGITAL_SIGNATURE_ESID :'DIGITAL_SIGNATURE_ESID';
  ELECTRONIC_SIGNATURE_ESID :'ELECTRONIC_SIGNATURE_ESID';
  INCLUDES_ESID :'INCLUDES_ESID';
  LOCATED_AT_ESID :'LOCATED_AT_ESID';
  LOCATION_ESID :'LOCATION_ESID';
  PUBLIC_KEY_ESID :'PUBLIC_KEY_ESID';
  SCHEMA_EKID :'SCHEMA_EKID';
  SIGNED_BY_ESID :'SIGNED_BY_ESID';
  STAFF_EKID :'STAFF_EKID';
  STAFF_ESID :'STAFF_ESID';
  VERIFIES_ESID :'VERIFIES_ESID';
  WITNESSES_ESID :'WITNESSES_ESID';
|};
type QueryStringParam = $Values<QueryStringParamEnum>;

// TODO: look into using Immutable.Map() or other possible "enum" libraries
const QueryStringParams :{|...QueryStringParamEnum |} = Object.freeze({
  CLIENTS_ESID: 'CLIENTS_ESID',
  CLIENT_EKID: 'CLIENT_EKID',
  CONSENT_FORM_ESID: 'CONSENT_FORM_ESID',
  CONSENT_FORM_SCHEMAS_ESID: 'CONSENT_FORM_SCHEMAS_ESID',
  DECRYPTED_BY_ESID: 'DECRYPTED_BY_ESID',
  DIGITAL_SIGNATURE_ESID: 'DIGITAL_SIGNATURE_ESID',
  ELECTRONIC_SIGNATURE_ESID: 'ELECTRONIC_SIGNATURE_ESID',
  INCLUDES_ESID: 'INCLUDES_ESID',
  LOCATED_AT_ESID: 'LOCATED_AT_ESID',
  LOCATION_ESID: 'LOCATION_ESID',
  PUBLIC_KEY_ESID: 'PUBLIC_KEY_ESID',
  SCHEMA_EKID: 'SCHEMA_EKID',
  SIGNED_BY_ESID: 'SIGNED_BY_ESID',
  STAFF_EKID: 'STAFF_EKID',
  STAFF_ESID: 'STAFF_ESID',
  VERIFIES_ESID: 'VERIFIES_ESID',
  WITNESSES_ESID: 'WITNESSES_ESID',
});

export default QueryStringParams;
export type {
  QueryStringParam,
  QueryStringParamEnum,
};
